Add WithLabel list filter to serving client lib
knative/client pull request #1054
Opened 2020-10-08 11:38 UTC by zroubalik

Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

## Description

Adding `WithLabel` list filter to serving client lib, which is missing currently. This allows to filter lists by labels.

## Reference

Fixes #1053 

/lint

2020-10-08 12:38 UTC, navidshaikh approved these changes
/ok-to-test

2020-10-08 14:25 UTC, rhuss requested changes
Thanks ! Looks good, but could you please also add a test to client_test_mock.go and client_test.go ?

Also an entry in CHANGELOG.adoc would be cool

2020-10-09 01:08 UTC, maximilien requested changes
Thanks for contributions. Any way to add tests and show how to use this?

2020-10-09 08:54 UTC, zroubalik commented
I have added tests. Let me know if I should add anything else.

2020-10-09 10:49 UTC, navidshaikh approved these changes
lgtm, thanks @zroubalik ! can you please finalize the PR with a changelog entry in CHANGELOG.adoc ?

2020-10-09 10:59 UTC, zroubalik commented
@navidshaikh Changelog updated, let me know if you need anything else, thanks!

2020-10-09 11:25 UTC, zroubalik commented
/retest

2020-10-09 13:48 UTC, navidshaikh approved these changes
/lgtm
/approve

thanks @zroubalik for contribution, keep them coming! ;-)

2020-10-09 14:26 UTC, merged