Export test refactor
knative/client pull request #1069
Opened 2020-10-20 02:38 UTC by itsmurugappan

## Description

Refactor kn service export test to use helper functions from serving repo.

First and third commit - Has only vendor changes
Second commit - Has the test refactor changes

2020-10-20 05:58 UTC, navidshaikh requested changes
Thanks for promoting these utils to `lib`!

There was a fix landed for the failure in e2e (against master), looks like that's lost during refactor ?
```
        --- knExport
        +++ &actSvc
        [...]

        - 						EnableServiceLinks:        nil,
        + 						EnableServiceLinks:        &false,
        [...]
```

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +type ExpectedServiceListOption func(*servingv1.ServiceList)
@itsmurugappan : We should add the description to all these exported types as they're in `lib` and are expected to be consumed by plugins etc, it helps in the editor.

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +func Cfg(co ...servingtest.ConfigOption) *servingv1.ConfigurationSpec {
how about renaming this to `ServiceConfig` ?

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +}
move the var at the top of the file ?

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +	TimeoutSeconds: ptr.Int64(300),
should use `DefaultRevisionTimeoutSeconds` constant from `knative.dev/serving/pkg/apis/config/defaults.go`

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +//GetSvcWithOptions returns ksvc with options provided
```suggestion
// GetSvcWithOptions returns ksvc with options provided
```

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +func WithTrafficSplit(revisions []string, percentages []int, tags []string) servingtest.ServiceOption {
```suggestion
func WithTrafficSpec(revisions []string, percentages []int, tags []string) servingtest.ServiceOption {
```

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +func GetRev(name string, options ...servingtest.RevisionOption) servingv1.Revision {
above, `Cfg` is used to build the configuration and here `GetRev`; all these builder utils should follow the same pattern, IMO we should avoid short names as well. 
wdyt about `BuildRevision` / `BuildConfiguration`?
I'd also avoid `Get` verb here as that denote to client GET call.

2020-10-20 05:58 UTC, navidshaikh commented on lib/test/service.go
> +	return *rev
may pass the pointer instead ? (like done for Configuration above)

2020-10-20 20:20 UTC, maximilien approved these changes
LGTM

Wonder if these vendor changes could have been part of a separate commit/PR?. Never easy to review... Anyhow.

2020-10-26 05:01 UTC, navidshaikh requested changes
a few places left in the code which can be aligned with the latest improvements made to the PR, i.e. to use full name `Revision` over `Rev`. Also, if the builder function takes a single object of a type, IMO we should consider using singular name for the function, for example `WithRevision`.

2020-10-30 20:42 UTC, maximilien commented
@itsmurugappan you need to rebase to pickup latest deps

2020-10-31 18:02 UTC, itsmurugappan commented
/test pull-knative-client-build-tests

2020-11-02 13:36 UTC, navidshaikh approved these changes
/lgtm
/approve

Thank you @itsmurugappan for the refactor! 
There are a few other parts for example the flags definition etc that we'd need regroup in a better way, lets talk about it in upcoming WG call.

2020-11-02 13:37 UTC, navidshaikh commented
@itsmurugappan : also please send another with an entry in CHANGELOG :-)

2020-11-02 13:47 UTC, itsmurugappan commented
sure @navidshaikh can include the changelog and other changes in the pr for bug fix #1087

2020-11-02 14:47 UTC, itsmurugappan commented
/test pull-knative-client-integration-tests

2020-11-02 15:21 UTC, merged