Add support for namespace for all commands that takes a --sink option
knative/client pull request #1264
Opened 2021-03-15 18:13 UTC by Kaustubh-pande

## Description
This PR will add support for the namespace that takes a  '--sink' option currently, we only resolve sink references in the current namespace but, with this PR user can able to refer the sink in another namespace.
if users pass the namespace `--sink ksvc:mysvc:my-namespace` which creates a destination that points to the my-namespace namespace, namespace support is optional, if the user not provided the namespace then-current namespace will be used

## Changes

* Add support for namespaces for all commands that take a --sink option

## Reference

Fixes #1143

2021-03-15 19:48 UTC, dsimansk commented
Thanks!
/ok-to-test

2021-03-16 01:39 UTC, navidshaikh commented
@Kaustubh-pande We should add e2e tests for this. e2e tests under dir `test/e2e/` operate under same namespace, so you can add one in smoke tests in `test/e2e-tests.sh`

2021-03-16 21:34 UTC, maximilien requested changes
Thanks for this and adding all tests. Leaving it to others to review since I did not have a need for it but I can see the value

2021-03-18 11:42 UTC, dsimansk approved these changes
/lgtm

@navidshaikh could take a final look pls?

2021-03-18 11:42 UTC, dsimansk commented
/hold

2021-03-18 12:28 UTC, navidshaikh requested changes
a nit otherwise lgtm

2021-03-18 12:28 UTC, navidshaikh commented on pkg/kn/commands/flags/sink.go
> +		"'" + flag + " ksvc:mysvc:mynamespace' you can create a destination which points to another namespace, " +
```suggestion
		"'" + flag + " ksvc:mysvc:mynamespace' for a Knative service 'mysvc' in another namespace 'mynamespace', " +
```

2021-03-18 12:28 UTC, navidshaikh commented on pkg/kn/commands/flags/sink.go
> +		"'" + flag + " ksvc:mysvc:mynamespace' you can create a destination which points to another namespace, " +
to align with other examples for sink flag

2021-03-18 13:40 UTC, dsimansk commented
It should be good to go as Navid's last comment was addressed.
/lgtm
/unhold

2021-03-18 13:41 UTC, merged

2021-03-23 10:15 UTC, rhuss commented
@dsimansk @navidshaikh @Kaustubh-pande I see an issue here when using a sink without a prefix (which is a ksvc) with a namespace. How to distinguish this from the case prefix + service without namespace ?

I.e. given `a:b`, is `a` a prefix and `b` the name of the object or is `a` a KService name and `b` a namespace ?

2021-03-23 11:20 UTC, navidshaikh commented
@rhuss : Correct. When referring to knative service without prefix, it has to be in the same namespace else for knative service in different namespace, `prefix:name:namespace` combination must be provided. We'd need to update the help message for the flag.

2021-03-23 11:28 UTC, dsimansk commented
@rhuss nice catch! We should probably update the error [message](https://github.com/knative/client/blob/main/pkg/kn/commands/flags/sink.go#L110) as well.

2021-03-23 13:17 UTC, rhuss commented
> @rhuss : Correct. When referring to knative service without prefix, it has to be in the same namespace else for knative service in different namespace, prefix:name:namespace combination must be provided. We'd need to update the help message for the flag.

Do we get also an error when our service is called `broker` ? I.e. for `broker:bla` (i.e. referring to a service "broker" in namespace "bla") we don't get an error even we should, right ? but that's hard to detect.

2021-03-23 13:25 UTC, navidshaikh commented
> Do we get also an error when our service is called broker ? I.e. for broker:bla (i.e. referring to a service "broker" in namespace "bla") we don't get an error even we should, right ?

In this case, it'd try to resolve broker `bla`, and upon not finding one it'd fail with not found error.