Update Eventing Sources API to v1
knative/client pull request #1299
Opened 2021-04-30 09:50 UTC by dsimansk

## Description

Follow-up on recent `v1alpha1` removal from Eventing main.
https://github.com/knative/eventing/pull/5318

## Changes

* Update to `APIServerSource, ContainerSource, PingSource & SinkBinding` API to `sources/v1`

/cc @knative/client-reviewers

2021-04-30 10:43 UTC, dsimansk commented
There's one open question though. PingSource was promoted to `v1` API just know, that why integration test are failing currently. That also implies that we can't use PingSource v1 on `0.22`, breaking the backward compatibility, therefore we need to keep PingSource at `v1beta2` for now. (applying the common client API policy keeping the lowest version until available)

@rhuss @maximilien any objections to the above? I'm mainly asking due to implications for `1.0` release etc.

2021-04-30 10:58 UTC, rhuss commented
Yeah, let's stay with PingSource v1beta2.

If Eventing goes to Knative 1.0 with v1beta2, too, I don't see any problems to use this for a 1.0 client.

2021-04-30 10:59 UTC, rhuss commented
@lionelvillard Are there any plans for Evention 1.0 to remove PingSource v1beta2, too ?

2021-04-30 12:04 UTC, lionelvillard commented
> @lionelvillard Are there any plans for Evention 1.0 to remove PingSource v1beta2, too ?

We have to keep v1beta2 for at least of couple of releases.

2021-04-30 13:42 UTC, dsimansk commented
/retest

2021-04-30 15:10 UTC, rhuss commented on pkg/kn/commands/source/ping/create_test.go
> +		TypeMeta:   metav1.TypeMeta{Kind: "Service", APIVersion: "serving.knative.dev/v1beta2"},
Serving v1beta2 ?

2021-04-30 15:13 UTC, rhuss requested changes
Looks good, however while cross checking it looks like that there has been a gotcha when reverting from v1 back to v1beta2 for the ping source (see comment inline). Not sure if other parts are affected, too.

2021-04-30 15:16 UTC, dsimansk commented on pkg/kn/commands/source/ping/create_test.go
> +		TypeMeta:   metav1.TypeMeta{Kind: "Service", APIVersion: "serving.knative.dev/v1beta2"},
:see_no_evil:

2021-04-30 16:31 UTC, rhuss commented
/retest

/lgtm
/approve

2021-04-30 21:12 UTC, maximilien reviewed
/ok-to-test
/lgtm

2021-05-02 12:18 UTC, rhuss commented
Looks like that the test indeed captured a valid issue:

```
source_list_test.go:85: assertion failed: 
        Actual output: NAME              TYPE         RESOURCE                          SINK   READY
        testpingsource0   PingSource   pingsources.sources.knative.dev          True
        
        Missing strings: ksvc:testsvc0
```

2021-05-02 19:45 UTC, dsimansk commented
> Looks like that the test indeed captured a valid issue:
> 
> ```
> source_list_test.go:85: assertion failed: 
>         Actual output: NAME              TYPE         RESOURCE                          SINK   READY
>         testpingsource0   PingSource   pingsources.sources.knative.dev          True
>         
>         Missing strings: ksvc:testsvc0
> ```
> 
> i.e. there is no output of the connected sink.

Well, this one was pretty hard to find actually. :sweat: 
The error is caused by failed unstructured conversion due to https://github.com/knative/eventing/commit/7c0b4770144e0fd3d026f1b4884242abaa9bd282.

2021-05-03 10:11 UTC, rhuss commented
> The only issue with 0.22.0 ...

That's fine I would say, as we can always say that's an issue with the backend and the fix is, to update the eventing backend to 0.22.1

2021-05-03 10:11 UTC, rhuss commented
/lgtm
/approve

2021-05-03 10:12 UTC, merged