WIP: Refactor waiting loop to use resourceVersion
knative/client pull request #1301
Opened 2021-05-04 20:48 UTC by dsimansk

## Description

## Changes

* Use `resourceVersion` in `*Delete` functions to get replay of events and prevent 
* Re-enable `retry` logic when watch channel is closed before timeout

## Reference

Fixes #1287 

/cc @rhuss

2021-05-05 20:53 UTC, maximilien requested changes
/ok-to-test
Left some feedback, especially related to some missing coverage. Of course we cannot cover all but at least see if you can solve one --- some are same in different locations.

2021-05-05 20:53 UTC, maximilien commented on pkg/wait/wait_for_ready.go
> +	defer watcher.Stop()
I can comment lines 150-152 and all tests passing. Similar on the other changes. My guess is that your tests are not covering the cases for failed timeout or similar?

2021-05-05 20:53 UTC, maximilien commented on pkg/wait/poll_watcher.go
> +	return polling, nil
I can comment this line and all tests pass. So missing coverage.

2021-05-05 20:53 UTC, maximilien commented on pkg/eventing/v1/client.go
> +	}
I can comment lines 253-255 and all tests passing

2021-05-05 20:53 UTC, maximilien commented on pkg/serving/v1/client.go
> +	}
Same as previous...

2021-05-06 14:28 UTC, dsimansk commented
> Left some feedback, especially related to some missing coverage. Of course we cannot cover all but at least see if you can solve one --- some are same in different locations.

Thanks, sure I'll take a pass on the test. The waiting loop is pretty tricky anyway, so more coverage is definitely good goal.

2021-05-07 10:04 UTC, rhuss commented
@dsimansk Thanks a lot ! I won't be able to make review this week, but will have a look asap early next week.

2021-05-07 15:40 UTC, maximilien commented
Sounds good. Thanks @dsimansk

2021-05-17 16:28 UTC, navidshaikh approved these changes
/lgtm

2021-05-17 17:17 UTC, merged