Use revision-name flag in kn service apply
knative/client pull request #1407
Opened 2021-07-29 11:59 UTC by vyasgun

## Description
`kn service apply --revision-name ` should use the revision name argument to generate revision name.

## Changes

* Removed the line setting the revision name to empty in apply flag.
* Tested that applying the same revision name to the service would not result in error as follows:
```
No changes to apply to service 'xyzsvc'.
Service 'xyzsvc' with latest revision 'xyzsvc-abcde' (unchanged) is available at URL:
http://xyzsvc.knativetutorial.192.168.49.2.nip.io

```

## Reference

Fixes #1184

2021-07-29 12:37 UTC, vyasgun commented
/retest

2021-07-29 15:48 UTC, dsimansk commented
@rhuss we've discussed with Gunjan in chat, that actual issue is waiting on `user-input`. AFAIK, there was no additional movement on it. 
Just to confirm. Can we close the PR for now until there's more info it's needed?

2021-07-29 15:48 UTC, dsimansk commented
/hold

2021-07-30 09:55 UTC, rhuss commented
The point is, that `kn service apply` das not support client-side revision naming. If you check the code, the name is always erased, even when provided on the command line.

My take is, that a client-side provided revision name does not fit to the _declararive model_ of `kn service apply`, which should be idempotent (e.g. if a apply command is given twice with the same arguments, the second command is a no-op)

Using client side revision naming is an _imperative way_ where the client dictates the name to use and you can't have idempotency because you have to always pick a new revision name.

So I'm in favor to close this PR.

2021-07-30 21:53 UTC, maximilien requested changes
Would it make sense to have a test change for this?

2021-08-03 07:46 UTC, dsimansk commented
Following on our discussion with @rhuss and @vyasgun, I'll close this PR. Any further comments can be added to original issue #1184.

/close

2021-08-03 07:51 UTC, closed without merging