Added range options to --scale
knative/client pull request #986
Opened 2020-08-20 18:46 UTC by mpetason

## Description

Adds range options to --scale. 

## Changes

* Adds three more options to --scale (1..5, 1.., ..5)

## Reference

Fixes #822

2020-08-20 18:46 UTC, mpetason commented
/wip

2020-08-20 20:55 UTC, maximilien commented
/ok-to-test

Ready for some reviews @mpetason?

2020-08-20 21:17 UTC, mpetason commented
Not ready for a review yet. I need to cleanup the range section and create a helper function. Right now it's just in an "it works" status and I wanted to show some work.

2020-08-20 21:41 UTC, maximilien commented on docs/cmd/kn_service_create.md
> +      --scale string                  Minimum and maximum number of replicas. Example: --scale 5 or --scale 1..5 or --scale 1.. or --scale ..5.
What does it mean to do —scale ..5 (up to five?). Maybe lets be clear with text...

2020-08-20 21:41 UTC, maximilien commented on pkg/kn/commands/service/configuration_edit_flags.go
> +	command.Flags().StringVar(&p.Scale, "scale", "", "Minimum and maximum number of replicas.")
Is “” a valid value? Perhaps use default?

2020-08-20 21:43 UTC, maximilien commented on pkg/kn/commands/service/configuration_edit_flags.go
> +				scaleInt, _ := strconv.Atoi(p.Scale)
Why are you ignoring the `Atoi(...)` error? Just catch and check it

2020-08-20 21:43 UTC, maximilien commented on pkg/kn/commands/service/configuration_edit_flags.go
> +				scaleMin, _ := strconv.Atoi(scaleParts[0])
Same here... don’t ignore errors

2020-08-25 10:52 UTC, rhuss commented
fyi, the fix for the failing CI is included as part of #902

2020-08-25 12:59 UTC, rhuss commented
/retest

2020-08-25 21:59 UTC, maximilien commented
Wonder if this is a flake

/test pull-knative-client-build-tests

2020-09-01 07:44 UTC, rhuss commented
@mpetason you would need to recreate the docs via `build.sh` and commit the generated/updated markdown files

2020-09-01 14:22 UTC, mpetason commented
@rhuss will do. I should have an update for this today.

2020-09-01 22:45 UTC, mpetason commented
Still WIP, need to update tests and fix how I'm checking for errors.

2020-09-02 18:39 UTC, mpetason commented
@maximilien @rhuss I think I'm ready for a review now. I need to update the docs (reverted back with the last build), but would like some pointers on changes I can make to the code/tests.

2020-09-14 05:48 UTC, daisy-ycguo requested changes
Thank you for the contributions. I think this PR looks good generally. I just left a few comments.

2020-09-14 05:48 UTC, daisy-ycguo commented on pkg/kn/commands/service/configuration_edit_flags.go
> +	command.Flags().StringVar(&p.Scale, "scale", "1", "Minimum and maximum number of replicas.")
I suggest to add a sample at the end of the explanation, e.g.
```
Minimum and maximum number of replicas. (e.g., 1..5).
```
in order to help end users understand the format clearly.

2020-09-14 05:48 UTC, daisy-ycguo commented on pkg/kn/commands/service/configuration_edit_flags.go
> +func (p *ConfigurationEditFlags) ScaleConversion(scale string) (scaleMin int, scaleMax int, err error) {
Do you want the method `ScaleConversion` to be visible outside package? If the method is not used by any other packages, I suggest to change the method name to start with a lower case letter, e.g. `scaleConversion`

2020-09-16 14:13 UTC, mpetason commented
/restest

2020-09-21 21:06 UTC, mpetason commented
I didn't rebase this correctly and have no clue how to fix it. I guess I need to close/delete this PR and try again?

2020-10-01 16:54 UTC, mpetason commented
Can't figure out how to fix the issue where there are so many files added. Tried a rebase but it doesn't look like that helped. Going to close this out for good and open a new PR with the same work.

2020-10-07 14:20 UTC, mpetason commented
Figured out how to clean this up after rebase. I'm probably going to close this out and re-open since I'm still running into conflicts with the command information files.

2020-10-15 15:56 UTC, closed without merging